
DROP TABLE IF EXISTS TIPO_CAMBIO;

CREATE TABLE TIPO_CAMBIO
(
	ID BIGINT NOT NULL,
	TIPO_MONEDA_ORIGEN VARCHAR(100),
	TIPO_MONEDA_DESTINO VARCHAR(100),
	VALOR DECIMAL(6,3),
	IS_ACTIVE    TINYINT NOT NULL,
	CREATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT   DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	PRIMARY KEY (ID)
);


INSERT INTO TIPO_CAMBIO(ID,TIPO_MONEDA_ORIGEN,TIPO_MONEDA_DESTINO, VALOR,IS_ACTIVE, CREATED_AT)
VALUES (1,'DOLAR','EURO', 0.8,1, CURRENT_TIMESTAMP());

INSERT INTO TIPO_CAMBIO(ID,TIPO_MONEDA_ORIGEN, TIPO_MONEDA_DESTINO, VALOR,IS_ACTIVE, CREATED_AT)
VALUES (2,'EURO','DOLAR', 1.08,1, CURRENT_TIMESTAMP());

INSERT INTO TIPO_CAMBIO(ID,TIPO_MONEDA_ORIGEN, TIPO_MONEDA_DESTINO, VALOR,IS_ACTIVE, CREATED_AT)
VALUES (3,'YENN', 'DOLAR', 0.03,1, CURRENT_TIMESTAMP());

INSERT INTO TIPO_CAMBIO(ID,TIPO_MONEDA_ORIGEN, TIPO_MONEDA_DESTINO, VALOR,IS_ACTIVE, CREATED_AT)
VALUES (4,'DOLAR', 'YENN', 0.8,1, CURRENT_TIMESTAMP());

INSERT INTO TIPO_CAMBIO(ID,TIPO_MONEDA_ORIGEN, TIPO_MONEDA_DESTINO, VALOR,IS_ACTIVE, CREATED_AT)
VALUES (5,'YENN', 'EURO', 0.03,1, CURRENT_TIMESTAMP());

INSERT INTO TIPO_CAMBIO(ID,TIPO_MONEDA_ORIGEN, TIPO_MONEDA_DESTINO, VALOR,IS_ACTIVE, CREATED_AT)
VALUES (6,'DOLAR', 'SOL', 0.8,1, CURRENT_TIMESTAMP());
	